name: Tests
on:
  push:
    branches: ['master']
  pull_request:

jobs:
  test_sqlite:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          ### TEST ALL RUBY VERSIONS, USE DEFAULT GEMFILE
          - ruby: "2.6"
          - ruby: "2.7"
          - ruby: "3.0"
          - ruby: "3.1"
          - ruby: "3.2"

          ### RAILS VERSION TESTING
          - ruby: "2.6"
            gemfile: gemfiles/sqlite3_ar_5.2_pt_12.0.gemfile
          - ruby: "2.6"
            gemfile: gemfiles/sqlite3_ar_6.0_pt_12.0.gemfile
          - ruby: "2.6"
            gemfile: gemfiles/sqlite3_ar_6.1_pt_12.0.gemfile
          - ruby: "3.2"
            gemfile: gemfiles/sqlite3_ar_7.0_pt_12.0.gemfile

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
      DB: sqlite

    steps:
    - uses: actions/checkout@v3

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true

    - name: Run tests
      run: |
        #bundle exec rake db:test:prepare
        bundle exec rake


  test_mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports: ['3306:3306']

    strategy:
      fail-fast: false
      matrix:
        include:
          ### RAILS VERSION TESTING
          ### DONT WORRY ABOUT TESTING ALL RUBY VERSIONS. THIS IS COVERED IN THE SQLITE3 TESTS
          - ruby: "2.6"
            gemfile: gemfiles/mysql2_ar_5.2_pt_12.0.gemfile
          - ruby: "2.6"
            gemfile: gemfiles/mysql2_ar_6.0_pt_12.0.gemfile
          - ruby: "2.6"
            gemfile: gemfiles/mysql2_ar_6.1_pt_12.0.gemfile
          - ruby: "3.2"
            gemfile: gemfiles/mysql2_ar_7.0_pt_12.0.gemfile

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
      DB: mysql

    steps:
    - uses: actions/checkout@v3

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true

    - name: Run tests
      env:
        DATABASE_URL: mysql2://root:password@127.0.0.1:3306/test
        RAILS_ENV: test
      run: |
        #bundle exec rake db:test:prepare
        bundle exec rake


  test_pg:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports: ['5432:5432']

    strategy:
      fail-fast: false
      matrix:
        include:
          ### RAILS VERSION TESTING
          ### DONT WORRY ABOUT TESTING ALL RUBY VERSIONS. THIS IS COVERED IN THE SQLITE3 TESTS
          - ruby: "2.6"
            gemfile: gemfiles/pg_ar_5.2_pt_12.0.gemfile
          - ruby: "2.6"
            gemfile: gemfiles/pg_ar_6.0_pt_12.0.gemfile
          - ruby: "2.6"
            gemfile: gemfiles/pg_ar_6.1_pt_12.0.gemfile
          - ruby: "3.2"
            gemfile: gemfiles/pg_ar_7.0_pt_12.0.gemfile

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
      DB: postgres

    steps:
    - uses: actions/checkout@v3

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:password@localhost:5432/test
        RAILS_ENV: test
      run: |
        #bundle exec rails db:test:prepare
        bundle exec rake
